/*******************************************************************************
 *     This file is part of ScienceGadgets, a collection of educational tools
 *     Copyright (C) 2012-2015 by John Gralyan
 *
 *     ScienceGadgets is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 *
 *     ScienceGadgets is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *     
 *     Contact us at info@sciencegadgets.org
 *******************************************************************************/
package com.sciencegadgets.client.algebra.transformations;

import static java.util.Arrays.asList;
import java.util.HashSet;
import java.util.List;

public enum Skill {

	// Evaluate
	FACTOR_NUMBERS(
			"Integer Factorization",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML7\" class=\"sg-in-equation Number\">8<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML9\" class=\"sg-in-equation Term\"><div id=\"ML12\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML13\" class=\"sg-in-term Operation\">·</div><div id=\"ML8\" class=\"sg-in-term Number\">4<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>"), //
	DIVIDE_NUMBERS(
			"Division",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML14\" class=\"sg-in-equation Fraction\"><div id=\"ML7\" class=\"sg-in-fraction-numerator Number\">8<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML16\" class=\"sg-in-fraction-denominator Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML8\" class=\"sg-in-equation Number\">4<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	EXPONENTIATE_NUMBERS(
			"Evaluate Exponents",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML17\" class=\"sg-in-equation Exponential\"><div id=\"ML20\" class=\"sg-in-exponential-base Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML19\" class=\"sg-in-exponential-exponent Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML21\" class=\"sg-in-equation Number\">9<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //

	// DROP
	DROP_CANCEL(
			"Cancelling Fractions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML24\" class=\"sg-in-equation Fraction\"><div id=\"ML26\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML27\" class=\"sg-in-fraction-denominator Variable\">a</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML28\" class=\"sg-in-equation Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	DROP_DIVIDE(
			"Division",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML14\" class=\"sg-in-equation Fraction\"><div id=\"ML7\" class=\"sg-in-fraction-numerator Number\">8<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML16\" class=\"sg-in-fraction-denominator Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML8\" class=\"sg-in-equation Number\">4<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	DROP_EXPONENTIAL(
			"Divide Exponentials",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML24\" class=\"sg-in-equation Fraction\"><div id=\"ML29\" class=\"sg-in-fraction-numerator Exponential\"><div id=\"ML26\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML31\" class=\"sg-in-exponential-exponent Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML32\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML27\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML34\" class=\"sg-in-exponential-exponent Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML36\" class=\"sg-in-equation Exponential\"><div id=\"ML35\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML38\" class=\"sg-in-exponential-exponent Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML24\" class=\"sg-in-equation Fraction\"><div id=\"ML29\" class=\"sg-in-fraction-numerator Exponential\"><div id=\"ML26\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML39\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML32\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML27\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML40\" class=\"sg-in-exponential-exponent Variable\">m</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML36\" class=\"sg-in-equation Exponential\"><div id=\"ML35\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML42\" class=\"sg-in-exponential-exponent Sum\"><div class=\"sg-fenced\"><div id=\"ML41\" class=\"sg-in-sum Variable\">n</div><div id=\"ML43\" class=\"sg-in-sum Operation\">-</div><div id=\"ML45\" class=\"sg-in-sum Variable\">m</div></div></div></div></div>"), //
	DROP_LOG(
			"Divide Logs",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML50\" class=\"sg-in-equation Fraction\"><div id=\"ML48\" class=\"sg-in-fraction-numerator Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML49\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML56\" class=\"sg-in-fraction-denominator Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML58\" class=\"sg-in-log Variable\">e</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML54\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">e</div><div id=\"ML59\" class=\"sg-in-log Variable\">a</div></div></div>"), //
	DROP_TRIG(
			"Trigonometric Identities",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML62\" class=\"sg-in-equation Fraction\"><div id=\"ML64\" class=\"sg-in-fraction-numerator Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML65\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML66\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">cos</div><div id=\"ML67\" class=\"sg-in-trig Variable\">θ</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML68\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">tan</div><div id=\"ML69\" class=\"sg-in-trig Variable\">θ</div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML73\" class=\"sg-in-equation Fraction\"><div id=\"ML72\" class=\"sg-in-fraction-numerator Trig\"><div class=\"sg-functionName\">cos</div><div id=\"ML76\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML75\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML77\" class=\"sg-in-trig Variable\">θ</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML79\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">cot</div><div id=\"ML80\" class=\"sg-in-trig Variable\">θ</div></div></div>"), //
	SIMPLIFY_FRACTIONS(
			"Simplify Fractions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML84\" class=\"sg-in-equation Fraction\"><div id=\"ML83\" class=\"sg-in-fraction-numerator Number\">8<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML86\" class=\"sg-in-fraction-denominator Number\">6<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML88\" class=\"sg-in-equation Fraction\"><div id=\"ML87\" class=\"sg-in-fraction-numerator Number\">4<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML90\" class=\"sg-in-fraction-denominator Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>"), //

	// ADD
	ADD(
			"Addition",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML92\" class=\"sg-in-sum Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">+</div><div id=\"ML96\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML98\" class=\"sg-in-equation Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML92\" class=\"sg-in-sum Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">-</div><div id=\"ML96\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML99\" class=\"sg-in-equation Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML100\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">+</div><div id=\"ML96\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML101\" class=\"sg-in-equation Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML100\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">-</div><div id=\"ML96\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML102\" class=\"sg-in-equation Number\"><div class=\"sg-fenced\">-5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML103\" class=\"sg-in-sum Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">-</div><div id=\"ML104\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML105\" class=\"sg-in-equation Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML93\" class=\"sg-in-equation Sum\"><div id=\"ML106\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML94\" class=\"sg-in-sum Operation\">-</div><div id=\"ML104\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML107\" class=\"sg-in-equation Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	ADD_WITH_ZERO("Addition with Zero", asList(ADD)), //
	ADD_NUMBERS_10("Addition"), //
	ADD_NUMBERS_100("Addition", asList(ADD_NUMBERS_10)), //
	ADD_NUMBERS_LARGE("Addition", asList(ADD_NUMBERS_100)), //
	SUBTRACTION("Subtraction", asList(ADD)), //
	ADDITION_WITH_NEGATIVES("Addition with negatives", asList(SUBTRACTION)), //
	ADD_FRACTIONS("Fraction Addition",
			asList(ADD),//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML111\" class=\"sg-in-equation Sum\"><div id=\"ML109\" class=\"sg-in-sum Fraction\"><div id=\"ML116\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML118\" class=\"sg-in-fraction-denominator Variable\">c</div></div><div id=\"ML112\" class=\"sg-in-sum Operation\">+</div><div id=\"ML114\" class=\"sg-in-sum Fraction\"><div id=\"ML117\" class=\"sg-in-fraction-numerator Variable\">b</div><div id=\"ML119\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML120\" class=\"sg-in-equation Fraction\"><div id=\"ML124\" class=\"sg-in-fraction-numerator Sum\"><div id=\"ML123\" class=\"sg-in-sum Variable\">a</div><div id=\"ML125\" class=\"sg-in-sum Operation\">+</div><div id=\"ML127\" class=\"sg-in-sum Variable\">b</div></div><div id=\"ML122\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div>"), //
	COMMON_DENOMINATOR(
			"Common denominator",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML111\" class=\"sg-in-equation Sum\"><div id=\"ML109\" class=\"sg-in-sum Fraction\"><div id=\"ML116\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML118\" class=\"sg-in-fraction-denominator Variable\">c</div></div><div id=\"ML112\" class=\"sg-in-sum Operation\">+</div><div id=\"ML117\" class=\"sg-in-sum Variable\">b</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML128\" class=\"sg-in-equation Sum\"><div id=\"ML120\" class=\"sg-in-sum Fraction\"><div id=\"ML123\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML122\" class=\"sg-in-fraction-denominator Variable\">c</div></div><div id=\"ML129\" class=\"sg-in-sum Operation\">+</div><div id=\"ML136\" class=\"sg-in-sum Fraction\"><div id=\"ML132\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML131\" class=\"sg-in-term Variable\">b</div><div id=\"ML133\" class=\"sg-in-term Operation\">·</div><div id=\"ML135\" class=\"sg-in-term Variable\">c</div></div><div id=\"ML138\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div></div>"), //
	COMBINE_LIKE_TERMS("Combining Like Terms",
			asList(ADD),//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML142\" class=\"sg-in-equation Sum\"><div id=\"ML145\" class=\"sg-in-sum Term\"><div id=\"ML141\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML146\" class=\"sg-in-term Operation\">·</div><div id=\"ML148\" class=\"sg-in-term Variable\">a</div></div><div id=\"ML143\" class=\"sg-in-sum Operation\">+</div><div id=\"ML150\" class=\"sg-in-sum Term\"><div id=\"ML149\" class=\"sg-in-term Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML151\" class=\"sg-in-term Operation\">·</div><div id=\"ML153\" class=\"sg-in-term Variable\">a</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML155\" class=\"sg-in-equation Term\"><div id=\"ML154\" class=\"sg-in-term Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML156\" class=\"sg-in-term Operation\">·</div><div id=\"ML158\" class=\"sg-in-term Variable\">a</div></div></div>"), //
	FACTOR_POLYNOMIAL(
			"Factor Polynomial",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML142\" class=\"sg-in-equation Sum\"><div id=\"ML145\" class=\"sg-in-sum Term\"><div id=\"ML148\" class=\"sg-in-term Variable\">a</div><div id=\"ML164\" class=\"sg-in-term Operation\">·</div><div id=\"ML166\" class=\"sg-in-term Variable\">x</div></div><div id=\"ML143\" class=\"sg-in-sum Operation\">+</div><div id=\"ML150\" class=\"sg-in-sum Term\"><div id=\"ML153\" class=\"sg-in-term Variable\">a</div><div id=\"ML165\" class=\"sg-in-term Operation\">·</div><div id=\"ML167\" class=\"sg-in-term Variable\">y</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML155\" class=\"sg-in-equation Term\"><div id=\"ML158\" class=\"sg-in-term Variable\">a</div><div id=\"ML168\" class=\"sg-in-term Operation\">·</div><div id=\"ML161\" class=\"sg-in-term Sum\"><div class=\"sg-fenced\"><div id=\"ML169\" class=\"sg-in-sum Variable\">x</div><div id=\"ML162\" class=\"sg-in-sum Operation\">+</div><div id=\"ML170\" class=\"sg-in-sum Variable\">y</div></div></div></div></div>"), //
	ADD_LOGS(
			"Log Addition",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML174\" class=\"sg-in-equation Sum\"><div id=\"ML173\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML179\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML175\" class=\"sg-in-sum Operation\">+</div><div id=\"ML177\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML180\" class=\"sg-in-log Variable\">b</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML178\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML182\" class=\"sg-in-log Term\"><div id=\"ML181\" class=\"sg-in-term Variable\">a</div><div id=\"ML183\" class=\"sg-in-term Operation\">·</div><div id=\"ML185\" class=\"sg-in-term Variable\">b</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML174\" class=\"sg-in-equation Sum\"><div id=\"ML173\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML179\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML175\" class=\"sg-in-sum Operation\">-</div><div id=\"ML177\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML180\" class=\"sg-in-log Variable\">b</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML178\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML186\" class=\"sg-in-log Fraction\"><div id=\"ML181\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML188\" class=\"sg-in-fraction-denominator Variable\">b</div></div></div></div>"), //

	// BOTH SIDES
	BOTH_SIDES_ADD("Solving Equations Addition"), //
	BOTH_SIDES_SUBTRACT("Solving Equations Subtraction"), //
	BOTH_SIDES_MULTIPLY("Solving Equations Multiply"), //
	BOTH_SIDES_DIVIDE("Solving Equations Divide"), //
	BOTH_SIDES_INVERSE_EXPONENT("Solving Equations Exponential"), //
	BOTH_SIDES_RAISE("Solving Equations Raise Both Sides"), //
	BOTH_SIDES_LOG("Solving Equations Logs"), //
	BOTH_SIDES_INVERSE_TRIG("Solving Equations Inverse Trig"), //

	EXPONENT_EXPAND(
			"Expand Exponential",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML192\" class=\"sg-in-equation Exponential\"><div id=\"ML191\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML195\" class=\"sg-in-exponential-exponent Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML196\" class=\"sg-in-equation Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML192\" class=\"sg-in-equation Exponential\"><div id=\"ML191\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML197\" class=\"sg-in-exponential-exponent Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML198\" class=\"sg-in-equation Variable\">a</div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML192\" class=\"sg-in-equation Exponential\"><div id=\"ML191\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML199\" class=\"sg-in-exponential-exponent Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML200\" class=\"sg-in-equation Term\"><div id=\"ML198\" class=\"sg-in-term Variable\">a</div><div id=\"ML201\" class=\"sg-in-term Operation\">·</div><div id=\"ML203\" class=\"sg-in-term Variable\">a</div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML192\" class=\"sg-in-equation Exponential\"><div id=\"ML191\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML204\" class=\"sg-in-exponential-exponent Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML200\" class=\"sg-in-equation Term\"><div id=\"ML198\" class=\"sg-in-term Variable\">a</div><div id=\"ML201\" class=\"sg-in-term Operation\">·</div><div id=\"ML203\" class=\"sg-in-term Variable\">a</div><div id=\"ML205\" class=\"sg-in-term Operation\">·</div><div id=\"ML211\" class=\"sg-in-term Variable\">a</div><div id=\"ML207\" class=\"sg-in-term Operation\">·</div><div id=\"ML212\" class=\"sg-in-term Variable\">a</div><div id=\"ML209\" class=\"sg-in-term Operation\">·</div><div id=\"ML213\" class=\"sg-in-term Variable\">a</div></div></div>"), //
	EXPONENT_EXPONENTIATE(
			"Exponential with Exponent",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML215\" class=\"sg-in-equation Exponential\"><div id=\"ML192\" class=\"sg-in-exponential-base Exponential\"><div class=\"sg-fenced\"><div id=\"ML191\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML214\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML217\" class=\"sg-in-exponential-exponent Variable\">m</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML220\" class=\"sg-in-equation Exponential\"><div id=\"ML219\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML223\" class=\"sg-in-exponential-exponent Term\"><div class=\"sg-fenced\"><div id=\"ML222\" class=\"sg-in-term Variable\">n</div><div id=\"ML224\" class=\"sg-in-term Operation\">·</div><div id=\"ML226\" class=\"sg-in-term Variable\">m</div></div></div></div></div>"), //
	EXPONENT_NEGATIVE(
			"Negative Exponent",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML232\" class=\"sg-in-equation Exponential\"><div id=\"ML231\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML234\" class=\"sg-in-exponential-exponent Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML236\" class=\"sg-in-equation Fraction\"><div id=\"ML235\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML239\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML238\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML241\" class=\"sg-in-exponential-exponent Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML245\" class=\"sg-in-equation Fraction\"><div id=\"ML244\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML248\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML247\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML250\" class=\"sg-in-exponential-exponent Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML239\" class=\"sg-in-equation Exponential\"><div id=\"ML238\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML241\" class=\"sg-in-exponential-exponent Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML9\" class=\"sg-in-equation Fraction\"><div id=\"ML12\" class=\"sg-in-fraction-numerator Exponential\"><div id=\"ML8\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML14\" class=\"sg-in-exponential-exponent Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML11\" class=\"sg-in-fraction-denominator Variable\">b</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML16\" class=\"sg-in-equation Fraction\"><div id=\"ML15\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML19\" class=\"sg-in-fraction-denominator Term\"><div id=\"ML18\" class=\"sg-in-term Variable\">a</div><div id=\"ML20\" class=\"sg-in-term Operation\">·</div><div id=\"ML22\" class=\"sg-in-term Variable\">b</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML9\" class=\"sg-in-equation Fraction\"><div id=\"ML8\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML23\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML11\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML25\" class=\"sg-in-exponential-exponent Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML19\" class=\"sg-in-equation Term\"><div id=\"ML18\" class=\"sg-in-term Variable\">a</div><div id=\"ML20\" class=\"sg-in-term Operation\">·</div><div id=\"ML22\" class=\"sg-in-term Variable\">b</div></div></div>"), //
	EXPONENT_EXPRESSION(
			"Expression with Exponent",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML31\" class=\"sg-in-equation Exponential\"><div id=\"ML26\" class=\"sg-in-exponential-base Term\"><div class=\"sg-fenced\"><div id=\"ML8\" class=\"sg-in-term Variable\">a</div><div id=\"ML27\" class=\"sg-in-term Operation\">·</div><div id=\"ML29\" class=\"sg-in-term Variable\">b</div></div></div><div id=\"ML33\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML19\" class=\"sg-in-equation Term\"><div id=\"ML37\" class=\"sg-in-term Exponential\"><div id=\"ML18\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML49\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML20\" class=\"sg-in-term Operation\">·</div><div id=\"ML39\" class=\"sg-in-term Exponential\"><div id=\"ML22\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML50\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML31\" class=\"sg-in-equation Exponential\"><div id=\"ML53\" class=\"sg-in-exponential-base Fraction\"><div class=\"sg-fenced\"><div id=\"ML8\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML55\" class=\"sg-in-fraction-denominator Variable\">b</div></div></div><div id=\"ML33\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML56\" class=\"sg-in-equation Fraction\"><div id=\"ML37\" class=\"sg-in-fraction-numerator Exponential\"><div id=\"ML18\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML49\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML59\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML58\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML61\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML31\" class=\"sg-in-equation Exponential\"><div id=\"ML9\" class=\"sg-in-exponential-base Fraction\"><div class=\"sg-fenced\"><div id=\"ML26\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML8\" class=\"sg-in-term Variable\">a</div><div id=\"ML27\" class=\"sg-in-term Operation\">·</div><div id=\"ML29\" class=\"sg-in-term Variable\">b</div></div><div id=\"ML30\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div><div id=\"ML33\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML43\" class=\"sg-in-equation Term\"><div id=\"ML34\" class=\"sg-in-term Fraction\"><div id=\"ML19\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML37\" class=\"sg-in-term Exponential\"><div id=\"ML18\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML49\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML20\" class=\"sg-in-term Operation\">·</div><div id=\"ML39\" class=\"sg-in-term Exponential\"><div id=\"ML22\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML50\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML41\" class=\"sg-in-fraction-denominator Exponential\"><div id=\"ML36\" class=\"sg-in-exponential-base Variable\">c</div><div id=\"ML51\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML44\" class=\"sg-in-term Operation\">·</div><div id=\"ML47\" class=\"sg-in-term Exponential\"><div id=\"ML46\" class=\"sg-in-exponential-base Variable\">d</div><div id=\"ML52\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div></div>"), //
	EXPONENT_BASE_ZERO(
			"Exponent Base Zero",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML65\" class=\"sg-in-equation Exponential\"><div id=\"ML64\" class=\"sg-in-exponential-base Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML67\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML68\" class=\"sg-in-equation Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
			EXPONENT_BASE_ONE(
					"Exponent Base Zero",//
					"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML65\" class=\"sg-in-equation Exponential\"><div id=\"ML64\" class=\"sg-in-exponential-base Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML67\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML68\" class=\"sg-in-equation Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	EXPONENTIAL_INVERSE(
			"Exponential Inverse",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML71\" class=\"sg-in-equation Exponential\"><div id=\"ML74\" class=\"sg-in-exponential-base Number\">10<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML73\" class=\"sg-in-exponential-exponent Log\"><div class=\"sg-fenced\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML75\" class=\"sg-in-log Variable\">a</div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML76\" class=\"sg-in-equation Variable\">a</div></div>"), //
	//

	CONVERSION("Unit Conversion"), //
	COMMUNATIVE_PROPERTY(
			"Communative Property",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML79\" class=\"sg-in-equation Term\"><div id=\"ML78\" class=\"sg-in-term Variable\">a</div><div id=\"ML80\" class=\"sg-in-term Operation\">·</div><div id=\"ML82\" class=\"sg-in-term Variable\">b</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML83\" class=\"sg-in-equation Term\"><div id=\"ML86\" class=\"sg-in-term Variable\">b</div><div id=\"ML87\" class=\"sg-in-term Operation\">·</div><div id=\"ML76\" class=\"sg-in-term Variable\">a</div></div></div>"), //
	//
	MULTIPLY(
			"Multiplication",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML90\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML94\" class=\"sg-in-term Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML95\" class=\"sg-in-equation Number\">6<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML96\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML94\" class=\"sg-in-term Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML97\" class=\"sg-in-equation Number\"><div class=\"sg-fenced\">-6<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML98\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML99\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML97\" class=\"sg-in-equation Number\"><div class=\"sg-fenced\">-6<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML100\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML99\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML101\" class=\"sg-in-equation Number\">6<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	MULTIPLY_WITH_ZERO(
			"Multiplication with Zero",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML102\" class=\"sg-in-term Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML103\" class=\"sg-in-term Variable\">a</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML105\" class=\"sg-in-equation Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	MULTIPLY_WITH_ONE(
			"Multiplication with One",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML106\" class=\"sg-in-term Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML103\" class=\"sg-in-term Variable\">a</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML107\" class=\"sg-in-equation Variable\">a</div></div>"), //
	MULTIPLY_WITH_NEGATIVE_ONE(
			"Multiplication with Negative One",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML108\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML109\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML110\" class=\"sg-in-equation Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML91\" class=\"sg-in-equation Term\"><div id=\"ML108\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML92\" class=\"sg-in-term Operation\">·</div><div id=\"ML111\" class=\"sg-in-term Sum\"><div class=\"sg-fenced\"><div id=\"ML109\" class=\"sg-in-sum Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML112\" class=\"sg-in-sum Operation\">+</div><div id=\"ML114\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML115\" class=\"sg-in-equation Sum\"><div id=\"ML110\" class=\"sg-in-sum Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML116\" class=\"sg-in-sum Operation\">-</div><div id=\"ML118\" class=\"sg-in-sum Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML119\" class=\"sg-in-equation Term\"><div id=\"ML108\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML120\" class=\"sg-in-term Operation\">·</div><div id=\"ML124\" class=\"sg-in-term Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML122\" class=\"sg-in-term Operation\">·</div><div id=\"ML125\" class=\"sg-in-term Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML126\" class=\"sg-in-equation Term\"><div id=\"ML110\" class=\"sg-in-term Number\"><div class=\"sg-fenced\">-2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML127\" class=\"sg-in-term Operation\">·</div><div id=\"ML129\" class=\"sg-in-term Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>"), //
	MULTIPLY_NUMBERS_TO_10("Multiplication"), //
	MULTIPLY_NUMBERS_TO_100("Multiplication", asList(MULTIPLY_NUMBERS_TO_10)), //
	MULTIPLY_NUMBERS_LARGE("Multiplication", asList(MULTIPLY_NUMBERS_TO_100)), //
	MULTIPLY_WITH_FRACTION(
			"Multiplication with a Fraction",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML133\" class=\"sg-in-equation Term\"><div id=\"ML132\" class=\"sg-in-term Variable\">a</div><div id=\"ML134\" class=\"sg-in-term Operation\">·</div><div id=\"ML137\" class=\"sg-in-term Fraction\"><div id=\"ML136\" class=\"sg-in-fraction-numerator Variable\">b</div><div id=\"ML139\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML145\" class=\"sg-in-equation Fraction\"><div id=\"ML141\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML140\" class=\"sg-in-term Variable\">a</div><div id=\"ML142\" class=\"sg-in-term Operation\">·</div><div id=\"ML144\" class=\"sg-in-term Variable\">b</div></div><div id=\"ML147\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div>"), //
	MULTIPLY_FRACTIONS(
			"Multiplication of Fractions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML133\" class=\"sg-in-equation Term\"><div id=\"ML148\" class=\"sg-in-term Fraction\"><div id=\"ML132\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML150\" class=\"sg-in-fraction-denominator Variable\">b</div></div><div id=\"ML134\" class=\"sg-in-term Operation\">·</div><div id=\"ML137\" class=\"sg-in-term Fraction\"><div id=\"ML151\" class=\"sg-in-fraction-numerator Variable\">c</div><div id=\"ML152\" class=\"sg-in-fraction-denominator Variable\">d</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML145\" class=\"sg-in-equation Fraction\"><div id=\"ML141\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML140\" class=\"sg-in-term Variable\">a</div><div id=\"ML142\" class=\"sg-in-term Operation\">·</div><div id=\"ML153\" class=\"sg-in-term Variable\">c</div></div><div id=\"ML154\" class=\"sg-in-fraction-denominator Term\"><div id=\"ML157\" class=\"sg-in-term Variable\">b</div><div id=\"ML155\" class=\"sg-in-term Operation\">·</div><div id=\"ML158\" class=\"sg-in-term Variable\">d</div></div></div></div>"), //
	MULTIPLY_DISTRIBUTE(
			"Distributive Property",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML162\" class=\"sg-in-equation Term\"><div id=\"ML161\" class=\"sg-in-term Variable\">a</div><div id=\"ML163\" class=\"sg-in-term Operation\">·</div><div id=\"ML166\" class=\"sg-in-term Sum\"><div class=\"sg-fenced\"><div id=\"ML165\" class=\"sg-in-sum Variable\">b</div><div id=\"ML167\" class=\"sg-in-sum Operation\">+</div><div id=\"ML169\" class=\"sg-in-sum Variable\">c</div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML175\" class=\"sg-in-equation Sum\"><div id=\"ML171\" class=\"sg-in-sum Term\"><div id=\"ML170\" class=\"sg-in-term Variable\">a</div><div id=\"ML172\" class=\"sg-in-term Operation\">·</div><div id=\"ML174\" class=\"sg-in-term Variable\">b</div></div><div id=\"ML176\" class=\"sg-in-sum Operation\">+</div><div id=\"ML179\" class=\"sg-in-sum Term\"><div id=\"ML178\" class=\"sg-in-term Variable\">a</div><div id=\"ML180\" class=\"sg-in-term Operation\">·</div><div id=\"ML182\" class=\"sg-in-term Variable\">c</div></div></div></div>"), //
	MULTIPLY_LOG_RULE(
			"Log Power Rule",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML186\" class=\"sg-in-equation Term\"><div id=\"ML185\" class=\"sg-in-term Variable\">a</div><div id=\"ML187\" class=\"sg-in-term Operation\">·</div><div id=\"ML189\" class=\"sg-in-term Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML190\" class=\"sg-in-log Variable\">b</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML191\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML193\" class=\"sg-in-log Exponential\"><div id=\"ML192\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML195\" class=\"sg-in-exponential-exponent Variable\">a</div></div></div></div>"), //
	MULTIPLY_COMBINE_BASES(
			"Multiplying with Similar Bases",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML199\" class=\"sg-in-equation Term\"><div id=\"ML203\" class=\"sg-in-term Exponential\"><div id=\"ML198\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML207\" class=\"sg-in-exponential-exponent Variable\">m</div></div><div id=\"ML200\" class=\"sg-in-term Operation\">·</div><div id=\"ML205\" class=\"sg-in-term Exponential\"><div id=\"ML202\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML208\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML210\" class=\"sg-in-equation Exponential\"><div id=\"ML209\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML213\" class=\"sg-in-exponential-exponent Sum\"><div class=\"sg-fenced\"><div id=\"ML212\" class=\"sg-in-sum Variable\">m</div><div id=\"ML214\" class=\"sg-in-sum Operation\">+</div><div id=\"ML216\" class=\"sg-in-sum Variable\">n</div></div></div></div></div>"), //
	MULTIPLY_COMBINE_EXPONENTS(
			"Multiplying with Similar Exponents",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML199\" class=\"sg-in-equation Term\"><div id=\"ML203\" class=\"sg-in-term Exponential\"><div id=\"ML198\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML223\" class=\"sg-in-exponential-exponent Variable\">n</div></div><div id=\"ML200\" class=\"sg-in-term Operation\">·</div><div id=\"ML205\" class=\"sg-in-term Exponential\"><div id=\"ML222\" class=\"sg-in-exponential-base Variable\">b</div><div id=\"ML224\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML219\" class=\"sg-in-equation Exponential\"><div id=\"ML225\" class=\"sg-in-exponential-base Term\"><div class=\"sg-fenced\"><div id=\"ML209\" class=\"sg-in-term Variable\">a</div><div id=\"ML226\" class=\"sg-in-term Operation\">·</div><div id=\"ML228\" class=\"sg-in-term Variable\">b</div></div></div><div id=\"ML229\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div>"), //
	MULTIPLY_COMBINE_BASES_ARITHMETIC(
			"Multiplying with Similar Bases",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML199\" class=\"sg-in-equation Term\"><div id=\"ML203\" class=\"sg-in-term Exponential\"><div id=\"ML198\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML217\" class=\"sg-in-exponential-exponent Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML200\" class=\"sg-in-term Operation\">·</div><div id=\"ML205\" class=\"sg-in-term Exponential\"><div id=\"ML202\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML218\" class=\"sg-in-exponential-exponent Number\">3<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML219\" class=\"sg-in-equation Exponential\"><div id=\"ML209\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML221\" class=\"sg-in-exponential-exponent Number\">5<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div>"),
	//
	DIVIDING_FRACTIONS(
			"Dividing Fractions Flip",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML233\" class=\"sg-in-equation Fraction\"><div id=\"ML232\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML235\" class=\"sg-in-fraction-denominator Fraction\"><div id=\"ML237\" class=\"sg-in-fraction-numerator Variable\">b</div><div id=\"ML238\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML240\" class=\"sg-in-equation Term\"><div id=\"ML239\" class=\"sg-in-term Variable\">a</div><div id=\"ML241\" class=\"sg-in-term Operation\">·</div><div id=\"ML244\" class=\"sg-in-term Fraction\"><div id=\"ML243\" class=\"sg-in-fraction-numerator Variable\">c</div><div id=\"ML246\" class=\"sg-in-fraction-denominator Variable\">b</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML233\" class=\"sg-in-equation Fraction\"><div id=\"ML252\" class=\"sg-in-fraction-numerator Fraction\"><div id=\"ML232\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML254\" class=\"sg-in-fraction-denominator Variable\">b</div></div><div id=\"ML235\" class=\"sg-in-fraction-denominator Fraction\"><div id=\"ML255\" class=\"sg-in-fraction-numerator Variable\">c</div><div id=\"ML256\" class=\"sg-in-fraction-denominator Variable\">d</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML257\" class=\"sg-in-equation Term\"><div id=\"ML244\" class=\"sg-in-term Fraction\"><div id=\"ML250\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML246\" class=\"sg-in-fraction-denominator Variable\">b</div></div><div id=\"ML258\" class=\"sg-in-term Operation\">·</div><div id=\"ML261\" class=\"sg-in-term Fraction\"><div id=\"ML260\" class=\"sg-in-fraction-numerator Variable\">d</div><div id=\"ML263\" class=\"sg-in-fraction-denominator Variable\">c</div></div></div></div>"), //
	DENIMINATOR_FLIP_MULTIPLY(
			"Dividing Fractions Flip",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML233\" class=\"sg-in-equation Fraction\"><div id=\"ML252\" class=\"sg-in-fraction-numerator Fraction\"><div id=\"ML232\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML254\" class=\"sg-in-fraction-denominator Variable\">b</div></div><div id=\"ML235\" class=\"sg-in-fraction-denominator Fraction\"><div id=\"ML255\" class=\"sg-in-fraction-numerator Variable\">c</div><div id=\"ML256\" class=\"sg-in-fraction-denominator Variable\">d</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML244\" class=\"sg-in-equation Fraction\"><div id=\"ML264\" class=\"sg-in-fraction-numerator Term\"><div id=\"ML250\" class=\"sg-in-term Variable\">a</div><div id=\"ML265\" class=\"sg-in-term Operation\">·</div><div id=\"ML272\" class=\"sg-in-term Variable\">d</div></div><div id=\"ML267\" class=\"sg-in-fraction-denominator Term\"><div id=\"ML246\" class=\"sg-in-term Variable\">b</div><div id=\"ML268\" class=\"sg-in-term Operation\">·</div><div id=\"ML271\" class=\"sg-in-term Variable\">c</div></div></div></div>"), //
	//
	TRIG_FUNCTIONS_INVERSE(
			"Inverse Trigonometric Functions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML275\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML276\" class=\"sg-in-trig Trig\"><div class=\"sg-functionName\">arcsin</div><div id=\"ML277\" class=\"sg-in-trig Variable\">θ</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML278\" class=\"sg-in-equation Variable\">θ</div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML281\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">arcsin</div><div id=\"ML275\" class=\"sg-in-trig Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML280\" class=\"sg-in-trig Variable\">θ</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML278\" class=\"sg-in-equation Variable\">θ</div></div>"), //
	TRIG_FUNCTIONS_RECIPROCAL(
			"Reciprocal Trigonometric Functions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML283\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML284\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML285\" class=\"sg-in-equation Fraction\"><div id=\"ML287\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML288\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">csc</div><div id=\"ML289\" class=\"sg-in-trig Variable\">θ</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML8\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">cos</div><div id=\"ML9\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML11\" class=\"sg-in-equation Fraction\"><div id=\"ML10\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML13\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">sec</div><div id=\"ML14\" class=\"sg-in-trig Variable\">θ</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML16\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">tan</div><div id=\"ML17\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML18\" class=\"sg-in-equation Fraction\"><div id=\"ML10\" class=\"sg-in-fraction-numerator Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML20\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">cot</div><div id=\"ML21\" class=\"sg-in-trig Variable\">θ</div></div></div></div>"), //
	TRIGONOMETRIC_FUNCTIONS(
			"Trigonometric Functions",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML16\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">tan</div><div id=\"ML17\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML24\" class=\"sg-in-equation Fraction\"><div id=\"ML22\" class=\"sg-in-fraction-numerator Trig\"><div class=\"sg-functionName\">sin</div><div id=\"ML23\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML26\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">cos</div><div id=\"ML27\" class=\"sg-in-trig Variable\">θ</div></div></div></div>",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML30\" class=\"sg-in-equation Trig\"><div class=\"sg-functionName\">cot</div><div id=\"ML31\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML34\" class=\"sg-in-equation Fraction\"><div id=\"ML32\" class=\"sg-in-fraction-numerator Trig\"><div class=\"sg-functionName\">csc</div><div id=\"ML33\" class=\"sg-in-trig Variable\">θ</div></div><div id=\"ML36\" class=\"sg-in-fraction-denominator Trig\"><div class=\"sg-functionName\">sec</div><div id=\"ML37\" class=\"sg-in-trig Variable\">θ</div></div></div></div>"), //
	//
	LOG_CHANGE_BASE(
			"Logarithm Change Base",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML41\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML44\" class=\"sg-in-equation Fraction\"><div id=\"ML42\" class=\"sg-in-fraction-numerator Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">e</div><div id=\"ML43\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML46\" class=\"sg-in-fraction-denominator Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">e</div><div id=\"ML47\" class=\"sg-in-log Number\">10<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div></div></div>"), //
	LOG_EVALUATE(
			"Evaluating Logarithms",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML54\" class=\"sg-in-log Number\">2<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML55\" class=\"sg-in-equation Number\">100<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	LOG_ONE(
			"Logarithm of One",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML56\" class=\"sg-in-log Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML57\" class=\"sg-in-equation Number\">0<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	LOG_POWER(
			"Logarithm Power Rule",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML59\" class=\"sg-in-log Exponential\"><div id=\"ML58\" class=\"sg-in-exponential-base Variable\">a</div><div id=\"ML61\" class=\"sg-in-exponential-exponent Variable\">n</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML63\" class=\"sg-in-equation Term\"><div id=\"ML62\" class=\"sg-in-term Variable\">n</div><div id=\"ML64\" class=\"sg-in-term Operation\">·</div><div id=\"ML66\" class=\"sg-in-term Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML67\" class=\"sg-in-log Variable\">a</div></div></div></div>"), //
	LOG_PRODUCT(
			"Logarithm Product Rule",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML73\" class=\"sg-in-log Term\"><div id=\"ML58\" class=\"sg-in-term Variable\">a</div><div id=\"ML74\" class=\"sg-in-term Operation\">·</div><div id=\"ML76\" class=\"sg-in-term Variable\">b</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML68\" class=\"sg-in-equation Term\"><div id=\"ML66\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML67\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML69\" class=\"sg-in-sum Operation\">+</div><div id=\"ML71\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML72\" class=\"sg-in-log Variable\">b</div></div></div></div>"), //
	LOG_QUOTIENT(
			"Logarithm Quotient Rule",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML77\" class=\"sg-in-log Fraction\"><div id=\"ML58\" class=\"sg-in-fraction-numerator Variable\">a</div><div id=\"ML79\" class=\"sg-in-fraction-denominator Variable\">b</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML80\" class=\"sg-in-equation Sum\"><div id=\"ML66\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML67\" class=\"sg-in-log Variable\">a</div></div><div id=\"ML81\" class=\"sg-in-sum Operation\">-</div><div id=\"ML83\" class=\"sg-in-sum Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML84\" class=\"sg-in-log Variable\">b</div></div></div></div>"), //
	LOG_SAME_BASE_ARGUMENT(
			"Logarithm Same Base as Argument",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML86\" class=\"sg-in-log Number\">10<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML88\" class=\"sg-in-equation Number\">1<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div></div>"), //
	LOG_INVERSE(
			"Inverse Logarithm",//
			"<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sg-Equation\"><div id=\"ML40\" class=\"sg-in-equation Log\"><div class=\"sg-functionName\">log</div><div class=\"sg-in-log-base\">10</div><div id=\"ML89\" class=\"sg-in-log Exponential\"><div id=\"ML86\" class=\"sg-in-exponential-base Number\">10<div class=\"sg-in-term unit\" style=\"font-size: 40%;\"></div></div><div id=\"ML91\" class=\"sg-in-exponential-exponent Variable\">a</div></div></div><div id=\"ML2\" class=\"sg-in-equation Operation\">=</div><div id=\"ML92\" class=\"sg-in-equation Variable\">a</div></div>");//

	private String[] exampleHTML;
	private List<Skill> prerequisiteSkills;

	private Skill(String search) {
	}

	private Skill(String search, String... exampleHTML) {
		this.exampleHTML = exampleHTML;
	}

	private Skill(String search, List<Skill> prerequisiteSkills,
			String... exampleHTML) {
		this.prerequisiteSkills = prerequisiteSkills;
		this.exampleHTML = exampleHTML;
	}

	private Skill(String search, List<Skill> prerequisiteSkills) {
		this.prerequisiteSkills = prerequisiteSkills;
	}

	// TODO
	public HashSet<Skill> getPrerequisiteSkills() {
		HashSet<Skill> preSkills = new HashSet<Skill>();
		// fillWithPrerequisiteSkills(preSkills);
		return preSkills;
	}

	// private void fillWithPrerequisiteSkills(HashSet<Skill> preSkills) {
	// for (Skill pSkill : prerequisiteSkills) {
	// preSkills.add(pSkill);
	// pSkill.fillWithPrerequisiteSkills(preSkills);
	// }
	// }

	public static final String GOOGLE_SEARCH_PREFIX = "https://www.google.com/#q=";

	public String getPage() {
		return GOOGLE_SEARCH_PREFIX
				+ toString().toLowerCase().replace("_", "+");
	}

	public String[] getExampleHTMLs() {
		return exampleHTML;
	}

}
